/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SwapClass } from "./models/readability-nav.types";
export namespace Components {
    interface ReadabilityNav {
    }
    interface ReadabilityNavOption {
        "description": string;
        "isSelected": boolean;
        "label": string;
    }
    interface ReadabilityNavToggle {
        "isExpanded": boolean;
        "label": string;
    }
}
declare global {
    interface HTMLReadabilityNavElement extends Components.ReadabilityNav, HTMLStencilElement {
    }
    var HTMLReadabilityNavElement: {
        prototype: HTMLReadabilityNavElement;
        new (): HTMLReadabilityNavElement;
    };
    interface HTMLReadabilityNavOptionElement extends Components.ReadabilityNavOption, HTMLStencilElement {
    }
    var HTMLReadabilityNavOptionElement: {
        prototype: HTMLReadabilityNavOptionElement;
        new (): HTMLReadabilityNavOptionElement;
    };
    interface HTMLReadabilityNavToggleElement extends Components.ReadabilityNavToggle, HTMLStencilElement {
    }
    var HTMLReadabilityNavToggleElement: {
        prototype: HTMLReadabilityNavToggleElement;
        new (): HTMLReadabilityNavToggleElement;
    };
    interface HTMLElementTagNameMap {
        "readability-nav": HTMLReadabilityNavElement;
        "readability-nav-option": HTMLReadabilityNavOptionElement;
        "readability-nav-toggle": HTMLReadabilityNavToggleElement;
    }
}
declare namespace LocalJSX {
    interface ReadabilityNav {
        "onOptionSelected"?: (event: CustomEvent<SwapClass>) => void;
    }
    interface ReadabilityNavOption {
        "description"?: string;
        "isSelected"?: boolean;
        "label"?: string;
        "onTriggerSelectOption"?: (event: CustomEvent<any>) => void;
    }
    interface ReadabilityNavToggle {
        "isExpanded"?: boolean;
        "label"?: string;
        "onTriggerToggle"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "readability-nav": ReadabilityNav;
        "readability-nav-option": ReadabilityNavOption;
        "readability-nav-toggle": ReadabilityNavToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "readability-nav": LocalJSX.ReadabilityNav & JSXBase.HTMLAttributes<HTMLReadabilityNavElement>;
            "readability-nav-option": LocalJSX.ReadabilityNavOption & JSXBase.HTMLAttributes<HTMLReadabilityNavOptionElement>;
            "readability-nav-toggle": LocalJSX.ReadabilityNavToggle & JSXBase.HTMLAttributes<HTMLReadabilityNavToggleElement>;
        }
    }
}
